language: generic
matrix:
  include:
    - script: make test
      env: JOB=Xcode
      os: osx
      osx_image: xcode8
    - script: swift build && swift test
      env: JOB=SPM
      os: osx
      osx_image: xcode8
      before_install:
        - make bootstrap
    - script: docker run -v `pwd`:/SourceKitten jpsim/sourcekit bash -c "cd /SourceKitten && swift build && swift test"
      env: JOB=Linux-Docker
      sudo: required
      services: docker
      before_install: docker pull jpsim/sourcekit
    - script: swift build && swift test
      env: JOB=Linux-Installer
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get install -y libblocksruntime0 libkqueue0
        - wget https://github.com/norio-nomura/docker-sourcekit-builder/releases/download/30p6/swift-3.0-PREVIEW-6-2576271-with-sourcekit.tar.gz
        - sudo tar zxvf swift-3.0-PREVIEW-6-2576271-with-sourcekit.tar.gz -C /
git:
  submodules: false
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
